### ISSUE TITLE
issue with double quotation

### ISSUE THREAD

**Issue by marcus-sds** [Altoros/cf-cassandra-broker#2]
Hi.
I checked the compatibility with scylladb and found issues.
the cassandra broker uses " only when grant command is used and " is not allowed at scylladb.
Can I know why it's using " instead of ' when using grant command?

**Comment by RMeharg** [comment]
To clarify, single quotes should be used at https://github.com/Altoros/cf-cassandra-broker/blob/3c1128b1159808c650478eee2be74c5992e2e14f/api/cassandra_service.go#L124 to fix this
